name: Lint and test

on:
  push:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: read

jobs:

  isort:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install isort
    - name: Check imports order
      run: isort -c --color .

  black:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install black
    - name: Check code format
      run: black --check --diff --color .

  flake8:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install flake8
    - name: Check code errors
      run: flake8 .

  pylint:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install pylint
    - name: Check code errors
      run: find . -type f -name '*.py' | xargs pylint --disable=missing-docstring --disable=too-few-public-methods

  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install coverage certifi six python_dateutil setuptools urllib3
    - name: Run tests
      run: coverage run -m unittest && coverage xml && coverage report
    - name: Save code coverage file
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.xml

  sonar:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
      - name: Check code errors
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
